### ISSUE TITLE
Mod screws up tooltips for other trims

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [dragon-forge/TrimsOnTools#2]
As the title says, the mod seems to screw up tooltips. 
![image](https://github.com/dragon-forge/TrimsOnTools/assets/132615999/4904d61a-efa6-4582-8839-0333be1094b9)
you get this, but it happens on every template tooltip, modded or vanilla.
this also causes looking up "trim" in JEI to not show anything, because it cant read the tooltip
this is mod version: `TrimsOnTools-1.21-21.0.0`

**Comment by Zeitheron** [comment]
Please provide game logs

**Comment by Kazuhiko-Gushiken** [comment]
@Zeitheron so sorry, it completely slipped my mind. https://gist.github.com/Kazuhiko-Gushiken/8b9f8eaff2252d38943d8d9a9085b3c6

**Comment by Zeitheron** [comment]
Fixed in [this commit](https://github.com/dragon-forge/TrimsOnTools/commit/2c240095d01bbba3885f93f2f95beea20251dd8b). I am currently waiting on the artist to finish two new trims before releasing the new version. :)
