### ISSUE TITLE
Enchant glint is far too strong

### ISSUE THREAD

**Issue by Nidoskull** [dragon-forge/TrimsOnTools#3]
As seen in the image, this enchantment glint is extremely strong. This tool was trimmed with gold, yet visually it appears to be Only Purple Now.
![enchantedtrim](https://github.com/user-attachments/assets/686ebecd-00e5-41cb-bfeb-70eaf510398a)

**Comment by Zeitheron** [comment]
This is vanilla overlay, and is not something that can be fixed from my end; You can reduce glint intensity in accessibility settings, though.
